sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: qAmH+W7hxWKh0Fdkk/LNg48WYhW99+16Zw99vPKk7BdQnmWZ1+Ly8svIHpdKAFlW/w16UmuM0XUZgiBAInoqpTb5kqR88FnMS4iVARvrepNMOu3zxgpe2Mu1czG+uvmo+1c60yItfORsKoZGpOgSIBtF/GWfEFOCjFZ1VhtqfiTdD5HhUfAa8J+DHxr6PHE99H40D6iJYyl5dc7JDTAZyz1vw1pWTqikQJ7jaJt1aIxIbDQBLT6iFU0EH/jz6RLk4Pe5PAKxXwMDYHl8Qq7GdXyd0O6LfI9hDiO8h4k7C4uy2epp4BXNwt20cBR9o6PCP2ZwjqM5vijMYhk0tkXIZNA51jMXwMwVDLK+XRBl8goyk6gcYcwqtq+tTCsW17kB/cWVVqsQbdvx3Bbe/cqWdw7NXD/fBcsJqkXg5JgftJvZTE9FCSE4PKKq24tp++Hih7AxWHxzMWCoLn3AlHjyrpb4O/be+hNwmeT87fEKLrMq9aPEQsYWcuehhfBg2HsjjaDTIWizBFSzdZbsDU7g8TKRZSfRE6JGekD2z2S+Mz7tTY8K7SDOd1VJbEM4U6b/Nw+FzsahjM/WevvyScTYAE691rqmYTvgKlYJc8jz0HBBQJuKxxJAt6xG1QDA2fEi7+0cMqtNesM19SKf8uLqQSq0/grfBnFT9oWPolUGfHA=
  - secure: PSBVHPx5vZ5P7wiT0fhLtnO+hPreL56ZeylaDxHPVIbCsCx1mbMVrkwhZxVZP8XkwzVyYk3S9eN9rJdpG/0MTLrH5SiHAj0yNGuedSSKkvVvcRX0xz6flb4OXEbMR9MlUS4FNLi6M4HAhqLxTqzkUOc1VOmpdXSFvMVbGwYewUe4ExRRd2EeOT8Hjy0l5t5BCCzGQmNnyYmvwB/FvPlPj+aCcXpL1UqduUQ6jwF4YBPBxvI1rzvdsAC7xk7ACyIoWj5ZVynoHBJf38iDzgs10UT5MSp6pjPo51pUvvyMrRVOmv+Qh3lrI+9nkI14bOITorzlOHW9TRpPeM87/wLhkH0KTRBC8FOtfESDGi35yqeW4g2ABdqOvan6eqfowmZ9dL2ATwQ3zWEV/KMgZffd+vfig0xgR0FOn1eDZ/K9lHzsKOPCeGdvmgeM0NDAJy8RhSYs6l2x6VmQ1FGXlJ0ntqjowTrvAOxW7lvEVtVu5doQjEdH3hnF++jhb9pOIb5KV6N2P3IEdocQZj09/5xswoHsQODqw+VxbCdkAZRknq5+Wc8/tvpCM8ad91GLBcaRUZT3lzAq7jFJbBiT/Uy1NN/efJtGIhtUifiNrCbfRE8xcCUKxefmjA9kgN8M6zbjU6fZumrtZtkMHMvmccFHbgfMfmsxPFPgm7UYt8OwfRM=
